config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, :path => '/', only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader

  # def self.search(search)
  #   if search
  #     if Cocktail.where(name: search).any?
  #       Cocktail.where(name: search)
  #     else
  #       Cocktail.all
  #     end
  #   else
  #     Cocktail.all
  #   end
  # end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses #dependent: :restrict_with_error
  before_destroy :check_for_doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :destroy]

  def index
    # @cocktails = Cocktail.search(params[:search])
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    @cocktail.save

    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktails_params
    params.require(:cocktail).permit(:name, :photo, :search)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(doses_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.save

    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to @dose.cocktail
  end

  private

  def doses_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1498&q=80);">
  <div class="container">
    <h1>The sexiest cocktails !</h1>
    <p>For your sexiest evenings...</p>
  </div>
  <!-- <div>
    <%= simple_form_for :search, url: cocktails_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search" id="search_query" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
    <% end %>
  </div> -->
</div>

<div class="container">
  <div class="cards">
    <% @cocktails.each do |cocktail| %>
    <div class="card-box">
      <%= link_to(cocktail_path(cocktail)) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.photo, height: 180, crop: :fill %>)">
        <%= cocktail.name.capitalize %>
      </div>
      <% end %>

      <div class="card-delete">
        <%= link_to(cocktail_path(cocktail), method: :delete, data: { confirm: "Are you sure?" }) do %>
        <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="cocktail-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?cocktail");>
  <div class="container">
    <h1>Add your sexy recipe</h1>
  </div>
</div>

<div class="container">
  <div class="form-box">
    <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="cocktail-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @cocktail.photo, height: 500, width: 600 %>)";>
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <div>
      <%= link_to 'Add a new Ingredient', new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="container">
  <ul>
    <% @cocktail.doses.each do |dose| %>
    <div class="card-product">
      <img src="https://source.unsplash.com/random/?cocktail" />
      <div class="card-product-infos">
        <h2><%= dose.ingredient.name %></h2>
        <p><%= dose.description %> <%= link_to(dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }) do %>
      <i class="far fa-trash-alt"></i>
      <% end %></p>
      </div>
    </div>
    <% end %>
  </ul>
</div>

app/views/doses/new.html.erb
<div class="cocktail-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @cocktail.photo, width: 1000, crop: :fill %>");>
</div>

<div class="container">
  <div class="form-box">
    <h2><%= @cocktail.name %></h2>
    <p>Add Ingredients</p>
  </div>

  <%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.association :ingredient, collection: Ingredient.all, prompt: "Choose an Ingredient"%>
  <%= f.input :description %>
  <%= f.submit "add an ingredient", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
    <div class="navbar-brand">
      <%= link_to(cocktails_path) do %>
      <%= image_tag('logo.png') %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'New Cocktail', new_cocktail_path, class: "nav-link"%>
        </li>
      </ul>
    </div>
  </div>

  <%= yield %>

  <div class="footer">
    <div class="footer-links">
      <a href="https://github.com/ma-v"><i class="fab fa-github"></i></a>
      <a href="https://www.instagram.com/mavrickmunoz/"><i class="fab fa-instagram"></i></a>
      <a href="https://www.linkedin.com/in/mavrickmunoz/"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This sexy website is made with sexiness by ma-v
    </div>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag "application" %>
</body>
</html>